### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pyario** [henry-anderson/PingAPI#8]
Hello i use this version: PingAPI 1.3.1 + 1.14.2 Spigot.

And i become a Error:

https://pastebin.com/LqybHpVj

Best Regards,

Pyario

**Comment by henry-anderson** [comment]
What version of ProtocolLib are you running?

**Comment by Pyario** [comment]
ProtocolLib version 4.5.0-SNAPSHOT
A development build for 1.14.2.

**Comment by henry-anderson** [comment]
I was unable to reproduce this issue. Try updating to PingAPI 1.3.2. If this doesn't work send me the entire startup log with the stacktrace.

**Comment by Pyario** [comment]
The error still remains ..
That comes only when you are in multiplayer and "refreshed" the Sever. Here are the classes + main class of my plugin maybe there is the error.

Classes : https://pastebin.com/zv2bzkEq


And if the server starts is not an error therefore I do not need to send the startup log.

**Comment by henry-anderson** [comment]
Your code looks fine. I compiled it and this was the output running 1.14.2.
<img src="https://i.imgur.com/j70V14K.png">
If possible would you be able to send me your server files? You can message me on Spigot [here](https://www.spigotmc.org/members/skionz.34955/) so they aren't public. Right now my guess is that there is another conflicting plugin.

**Comment by Pyario** [comment]
What exactly do you mean by server files? Do you mean that all files so worlds + plugins + configs etc.?

**Comment by henry-anderson** [comment]
I would mainly just need the plugins and configs

**Comment by Pyario** [comment]
Okay, give me a moment. I will write spigot to you under the name "sandi" and send them the link from the plugins folder.

**Comment by Pyario** [comment]
Oh I see a bug in the console I did not notice before ...

Error:

https://pastebin.com/Yc6bJ5BL

**Comment by henry-anderson** [comment]
Version 1.3.3 fixes this issue. See the documentation on the causes [here](https://github.com/henry-anderson/PingAPI/blob/4b83f9723fe52f0fa0aa5797787b50ab5cac77b3/PingAPI/src/org/henrya/pingapi/v1_14_R1/PingInjector.java#L45).
